name: a7_guis_task_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: 'dev_assets/gui.png'
  adaptive_icon_background: '#ceb1ff'
  adaptive_icon_foreground: 'dev_assets/gui-adaptive.png'

flutter:

  uses-material-design: true

  assets:
    - assets/gui.left.png    
    - assets/gui.left.thumbsUp.png

  